config/routes.rb
Rails.application.routes.draw do
  root to: "onduleurs#index"
  resources :onduleurs, only: [:index] do
    collection { post :import }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/date_for_total.rb
class DateForTotal < ApplicationRecord
end

app/models/onduleur.rb
class Onduleur < ApplicationRecord
  require 'csv'

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Onduleur.create! row.to_hash
    end
    onduleur_id = Onduleur.last.id
    date = Onduleur.last_date
    total = Onduleur.where("datetime LIKE ?", "#{date} %").sum(:energy)
    info = {date: date, total: total, onduleur_id: onduleur_id}
    DateForTotal.create(info)

  end

  def self.date_for_collection
    onduleurs = Onduleur.all
    date_time = onduleurs.map {|onduleur| onduleur[:datetime]}
    date_collection = []
    date_time.each do |dt|
      date = DateTime.strptime(dt, "%d/%m/%y %R")
      date.to_date
      date_collection << date.strftime("%d/%m/%y")
    end
    date_collection.uniq
  end

  def self.time_for_collection
    onduleurs = Onduleur.all
    date_time = onduleurs.map {|onduleur| onduleur[:datetime]}
    time_collection = []
    date_time.each do |dt|
      time = DateTime.strptime(dt, "%d/%m/%y %R")
      time.to_date
      time_collection << time.strftime("%R")
    end
    time_collection.uniq
  end

  private


  def self.last_date
    onduleur_last_date = Onduleur.last.datetime
    date = DateTime.strptime(onduleur_last_date, "%d/%m/%y %R")
    date.to_date
    last_date = date.strftime("%d/%m/%y")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/onduleur_controller.rb
class OnduleurController < ApplicationController
  def index
    @onduleur = Onduleur.all
  end

  def import
    Onduleur.import(params[:file])
    redirect_to root_url, notice: "File imported"
  end
end

app/controllers/onduleurs_controller.rb
class OnduleursController < ApplicationController
  def index
    if params.has_key?("date")
      @onduleurs_choosen = Onduleur.where("datetime LIKE ?", "#{params[:date][:date]} %" )
      @total_for_a_date = @onduleurs_choosen.sum(:energy)
    elsif params.has_key?("date_time")
      @onduleurs_choosen_by_time = Onduleur.where("datetime LIKE ?", "#{params[:date_time][:date]} #{params[:date_time][:time]}" )
      @total_for_a_hour = @onduleurs_choosen_by_time.sum(:energy)
    else
      @onduleurs = Onduleur.all
    end
  end

  def import
    Onduleur.import(params[:file])
    redirect_to root_url, notice: "File imported"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/onduleur_helper.rb
module OnduleurHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestOnduleur</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/onduleurs/import.html.erb
<h1>Onduleur#import</h1>
<p>Find me in app/views/onduleur/import.html.erb</p>

app/views/onduleurs/index.html.erb
<%= flash[:notice]%>
<h2>recherche pour un date spécifique</h2>
  <%= simple_form_for :date, url: onduleurs_path, method: :get, html: {class: 'form-inline'} do |f| %>
    <%= f.input :date, collection: Onduleur.date_for_collection,  prompt: "date ?" %>

    <%= f.button :submit, "Chercher" %>
  <% end %>
<br>
<h2>recherche pour une heure spécifique</h2>
  <%= simple_form_for :date_time, url: onduleurs_path, method: :get, html: {class: 'form-inline'} do |f| %>
    <%= f.input :date, collection: Onduleur.date_for_collection,  prompt: "date ?" %>
    <%= f.input :time, collection: Onduleur.time_for_collection, prompt: "heure ?" %>

    <%= f.button :submit, "Chercher" %>
  <% end %>

  <%= link_to 'tout les onduleurs', root_path %>


<table>
  <thead>
    <tr>
      <th>identifier</th>
      <th>date / time</th>
      <th>energy</th>
    </tr>
  </thead>
  <tbody>

  <% if params.has_key?("date") %>
    <% @onduleurs_choosen.each do |onduleur| %>
      <tr>
        <td><%= onduleur.identifier %></td>
        <td><%= onduleur.datetime %></td>
        <td><%= onduleur.energy %></td>
      </tr>
    <% end %>
    <h2>totalité de la consommation pour la date du <%= params[:date][:date] %>: <%= @total_for_a_date %></h2>

  <% elsif params.has_key?("date_time")%>
    <% @onduleurs_choosen_by_time.each do |onduleur| %>
      <tr>
        <td><%= onduleur.identifier %></td>
        <td><%= onduleur.datetime %></td>
        <td><%= onduleur.energy %></td>
      </tr>
      <% end %>
      <h2>totalité de la consommation pour la date du <%= params[:date_time][:date]%> à <%= params[:date_time][:time] %> : <%= @total_for_a_hour %></h2>

  <% else %>
    <% @onduleurs.each do |onduleur| %>
      <tr>
        <td><%= onduleur.identifier %></td>
        <td><%= onduleur.datetime %></td>
        <td><%= onduleur.energy %></td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>


<div>
<h3>Import the csv file</h3>
  <%=  form_tag import_onduleurs_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "import CSV" %>
  <% end %>
</div>